### ISSUE TITLE
Crash on 1.12.2 (forge 14.23.5.2808)

### ISSUE THREAD

**Issue by homemmakako** [truenachtara/Oversaturation#1]
Had just opened a world, full hunger, tried eating a vegetable from Pam's and my game crashed.

Here is the [Crashlog](https://pastebin.com/0tSb1B4T)

**Comment by Leo40Git** [comment]
Fixed version available here: https://drive.google.com/open?id=15ZMFHpQzEMnjjhzT2RyAjdXzSwcKLUBD
