### ISSUE TITLE
Mod is incompatible with AppleCore, and thus AppleSkin

### ISSUE THREAD

**Issue by GigaOtomia** [truenachtara/Oversaturation#3]
Crash text:
The game crashed whilst ticking player
Error: java.lang.RuntimeException: FoodStats has a null player field (this field is added by AppleCore at runtime) on player '' (class = com.nachie.oversaturation.FoodStats). This likely means that some mod has overloaded FoodStats, which is incompatible with AppleCore.

Crash log:
https://www.hastebin.com/ibatiwecez.rb

I'm using Forge 14.23.5.2820 on Minecraft 1.12.2, AppleCore 3.2.0, and Oversaturation 1.0, as you can see in the log.

**Comment by Leo40Git** [comment]
*psst, AppleCore is not required for AppleSkin*

**Comment by Leo40Git** [comment]
Fixed version available here: https://drive.google.com/open?id=15ZMFHpQzEMnjjhzT2RyAjdXzSwcKLUBD

**Comment by EvanHsieh0415** [comment]
bro, but other mods need
